---
#- name: Configure EC2 instances
- hosts: Ansible
  become: yes
  gather_facts: false

#  tasks:
#    - name: Install Python3 pip
#      ansible.builtin.apt:
#        name: python3-pip
#        state: present


---
# tasks file for build_remote_container
- block: ###RedHat###

    - name: RedHat os family - Install Docker
      yum:
        name:
          - docker
#          - python3-pip
#          - gnupg2
        state: latest
        update_cache: yes

    - name: Install python packages
#      pip:
#        name:
          - docker
#          - awscliv2
##        - pip
# #   - name: RedHat Start Apache RedHat
# #     service: name=docker state=started enabled=yes
  when: ansible_os_family == "RedHat"

- block: ###Debian###

    - name: Debian os family - Install Docker
      apt:
        name:
          - docker.io
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
#          - pass
#          - python3-docker
        state: latest
        update_cache: yes

    - name: Install python packages
      pip:
        name:
#          - awscliv2
          - docker
##        - pip
##    - name: Debian Start Apache
##      service: name=docker state=started enabled=yes
  when: ansible_os_family == "Debian"



- name: Start docker
  service: name=docker state=started enabled=yes

- name: Install docker-compose from official github repo
  get_url:
    url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Create and start services
  community.docker.docker_compose:
    project_src: /etc/monitoring
  register: output



- name: copy Docker Compose files
  copy:
    src: ${{ env.DEPLOYMENT_PATH }}
    dest: ${{ env.INSTANCE_PATH }}
  loop:
  - docker-compose.yml
