{
 "title": "Prometheus Blackbox Exporter",
 "description": "Prometheus Blackbox Exporter Overview",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "hostname",
    "query": {
     "query": "label_values(probe_success, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{hostname=~\"$hostname\", phase=\"rtt\"}"
    }
   ]
  },
  { "title": "LV-HikvisionNVR ServerRoom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"192.168.222.2\"}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"192.168.222.2\"})"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{hostname=~\"$hostname\"}"
    }
   ]
  },
  { "title": "LV-Fortigate ServerRoom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "interval" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"192.168.212.1\"}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"192.168.212.1\"})"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 23 },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance='192.168.212.1'}"
    }
   ]
  }
 ]
}