{
 "title": "Fortigate",
 "description": "Monitor your fortigate instances with grafana and prometheus via SNMP.\r\n\r\n\r\nTested with fortigate 1000D but should work well with other models.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "label_values(fgSysUpTime,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fgSysCpuUsage{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fgSysMemUsage{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fgSysUpTime{hostname=~\"$hostname\"}/100"
    }
   ]
  },
  {
   "title": "Inbound Bandwidth WAN-1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}[30m]) * on (ifIndex) group_left(ifName) ifName{hostname=~\"$hostname\",ifName=\"wan1\",job=\"fortigate_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "Inbound Bandwidth WAN-2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}[30m]) * on (ifIndex) group_left(ifName) ifName{hostname=~\"$hostname\",ifName=\"wan2\",job=\"fortigate_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "Alim status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fgHwSensorEntName{fgHwSensorEntName=~\"PS.+ Status\",instance=~\"$instance\"} / on(fgHwSensorEntIndex)  group_left(fgHwSensorEntValue) fgHwSensorEntValue)"
    }
   ]
  },
  {
   "title": "Version OS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fgSysVersion{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}",
     "legendFormat": "{{fgSysVersion}}"
    }
   ]
  },
  {
   "title": "Outbound Bandwidth WAN-1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}[30m]) * on (ifIndex) group_left(ifName) ifName{hostname=~\"$hostname\",ifName=\"wan1\",job=\"fortigate_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "Outbound Bandwidth WAN-2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}[30m]) * on (ifIndex) group_left(ifName) ifName{hostname=~\"$hostname\",ifName=\"wan2\",job=\"fortigate_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(fgSysCpuUsage{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}) / count(fgSysCpuUsage{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fgSysMemUsage{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inbound Bandwidth WAN-1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}[10m]) * on (ifIndex) group_left(ifName) ifName{hostname=~\"$hostname\",ifName=\"wan1\",job=\"fortigate_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "Outbound Bandwidth WAN-1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}[10m]) * on (ifIndex) group_left(ifName) ifName{hostname=~\"$hostname\",ifName=\"wan1\",job=\"fortigate_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "Inbound Bandwidth WAN-2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}[10m]) * on (ifIndex) group_left(ifName) ifName{hostname=~\"$hostname\",ifName=\"wan2\",job=\"fortigate_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "Outbound Bandwidth WAN-2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}[10m]) * on (ifIndex) group_left(ifName) ifName{hostname=~\"$hostname\",ifName=\"wan2\",job=\"fortigate_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "Inbound Bandwidth LAN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}[10m]) * on (ifIndex) group_left(ifName) ifName{hostname=~\"$hostname\",ifName=\"lan\",job=\"fortigate_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "Outbound Bandwidth LAN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}[10m]) * on (ifIndex) group_left(ifName) ifName{hostname=~\"$hostname\",ifName=\"lan\",job=\"fortigate_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "top 10 Interfaces Bytes/sec IN",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10,rate( ifHCInOctets{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}[10m]) * on (ifIndex) group_left(ifName) ifName{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"})\n",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "top 10 Interfaces Bytes/sec OUT",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10,rate( ifHCOutOctets{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"}[10m]) * on (ifIndex) group_left(ifName) ifName{hostname=~\"$hostname\",job=\"fortigate_snmp_exporter\"})",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Systeme",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum(fgSysCpuUsage{hostname=~\"$hostname\"}) / count(fgSysCpuUsage{hostname=~\"$hostname\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Status PS1",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fgHwSensorEntName{fgHwSensorEntName=\"PS1 Status\",hostname=~\"$hostname\"} / on(fgHwSensorEntIndex)  group_left(fgHwSensorEntValue) fgHwSensorEntValue",
       "legendFormat": "{{fgHwSensorEntValue}}"
      }
     ]
    },
    {
     "title": "Status PS2",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fgHwSensorEntName{fgHwSensorEntName=\"PS2 Status\",instance=~\"$instance\"} / on(fgHwSensorEntIndex)  group_left(fgHwSensorEntValue) fgHwSensorEntValue",
       "legendFormat": "{{fgHwSensorEntValue}}"
      }
     ]
    },
    {
     "title": "Temperature Ambiante PS1",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "fgHwSensorEntName{fgHwSensorEntName=\"PS1 Ambient Temp\",instance=~\"$instance\"} / on(fgHwSensorEntIndex)  group_left(fgHwSensorEntValue) fgHwSensorEntValue",
       "legendFormat": "{{fgHwSensorEntValue}}"
      }
     ]
    },
    {
     "title": "Temperature Ambiante PS2",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "fgHwSensorEntName{fgHwSensorEntName=\"PS2 Ambient Temp\",instance=~\"$instance\"} / on(fgHwSensorEntIndex)  group_left(fgHwSensorEntValue) fgHwSensorEntValue",
       "legendFormat": "{{fgHwSensorEntValue}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(fgSysCpuUsage{hostname=~\"$hostname\"}) / count(fgSysCpuUsage{hostname=~\"$hostname\"})"
      }
     ]
    },
    {
     "title": "PCB Temp.",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "fgHwSensorEntName{fgHwSensorEntName=\"PCB Temp.\",hostname=~\"$hostname\"} / on(fgHwSensorEntIndex)  group_left(fgHwSensorEntValue) fgHwSensorEntValue{hostname=~\"$hostname\"}",
       "legendFormat": "{{fgHwSensorEntValue}}"
      }
     ]
    }
   ]
  }
 ]
}