{
 "title": "Switches",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(ifHCInOctets,job)" } },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(ifAdminStatus,hostname)"
    }
   },
   { "name": "ifAlias", "label": "Port_Name", "query": { "query": "label_values(ifAlias)" } },
   { "name": "ifName", "label": "Port", "query": { "query": "label_values(ifName)" } }
  ]
 },
 "panels": [
  { "title": "$hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tpSysMonitorCpu5Minutes{hostname=~\"$hostname\",job=\"tplink_snmp_exporter\"}"
    },
    {
     "expr": "dEntityExtCpuUtilFiveMinutes{hostname=~\"$hostname\",job=\"tplink_snmp_exporter\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{hostname=~\"$hostname\"}/100"
    }
   ]
  },
  {
   "title": "all eth inbound",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{hostname=~\"$hostname\",ifName=~\"$ifName\",job=\"tplink_snmp_exporter\"}[5m])*8!=0",
     "legendFormat": "{{ifName}} "
    }
   ]
  },
  {
   "title": "all eth outbound",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{hostname=~\"$hostname\",ifName=~\"$ifName\",job=\"tplink_snmp_exporter\"}[5m])*8!=0",
     "legendFormat": "{{ifName}} "
    }
   ]
  },
  {
   "title": "all eth ifInErrors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifInErrors{hostname=~\"$hostname\",job=\"tplink_snmp_exporter\"}!=0",
     "legendFormat": "{{ifName}} "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifSpeed{hostname=~\"$hostname\",ifName=~\"$ifName\",job=\"tplink_snmp_exporter\"}/1000!=0",
     "legendFormat": "{{ifName}} "
    }
   ]
  }
 ]
}