groups:
- name: targets
  rules:
  - alert: monitor_service_down
    expr: up == 0
    for: 60s
    labels:
      severity: critical
    annotations:
      summary: "Monitor service non-operational"
      description: "Service {{ $labels.instance }} is down."

- name: host
  rules:
  - alert: high_cpu_load
    expr: node_load1 > 1.5
    for: 90s
    labels:
      severity: warning
    annotations:
      summary: "Server under high load"
      description: "Docker host is under high load, the avg load 1m is at {{ $value}}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

  - alert: high_memory_load
    expr: (sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100 > 85
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Server memory is almost full"
      description: "Docker host memory usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

  - alert: high_storage_load
    expr: (node_filesystem_size_bytes{fstype="xfs"} - node_filesystem_free_bytes{fstype="xfs"}) / node_filesystem_size_bytes{fstype="xfs"}  * 100 > 85
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Server storage is almost full"
      description: "Docker host storage usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

- name: containers
  rules:
###############grafana############################################################
#  - alert: grafana_down
#    expr: absent(up{job="grafana"})
#    for: 30s
#    labels:
#      severity: critical
#    annotations:
#      summary: "Grafana down"
#      description: "grafana container is down for more than 30 seconds."

#  - alert: grafana_high_cpu
#    expr: sum(rate(container_cpu_usage_seconds_total{name="grafana"}[1m])) / count(node_cpu_seconds_total{mode="system"}) * 100 > 10
#    for: 30s
#    labels:
#      severity: warning
#    annotations:
#      summary: "Grafana high CPU usage"
#      description: "grafana CPU usage is {{ humanize $value}}%."

#  - alert: grafana_high_memory
#    expr: sum(container_memory_usage_bytes{name="grafana"}) > 1200000000
#    for: 30s
#    labels:
#      severity: warning
#    annotations:
#      summary: "Grafana high memory usage"
#      description: "grafana memory consumption is at {{ humanize $value}}."

###############cadvisor############################################################
  - alert: cadvisor_down
    expr: absent(up{job="cadvisor"})
#absent(container_memory_usage_bytes{name="cadvisor"})
    for: 90s
    labels:
      severity: critical
    annotations:
      summary: "Cadvisor down"
      description: "cadvisor container is down for more than 90 seconds."

  - alert: cadvisor_high_cpu
    expr: sum(rate(container_cpu_usage_seconds_total{name="cadvisor"}[1m])) / count(node_cpu_seconds_total{mode="system"}) * 100 > 10
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Cadvisor high CPU usage"
      description: "cadvisor CPU usage is {{ humanize $value}}%."

  - alert: cadvisor_high_memory
    expr: sum(container_memory_usage_bytes{name="cadvisor"}) > 1200000000
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Cadvisor high memory usage"
      description: "cadvisor memory consumption is at {{ humanize $value}}."


###############nodeexporter for monitoring############################################################
  - alert: nodeexporter_down
    expr: absent(up{job="node_exporter"})
#absent(container_cpu_usage_seconds_total{name="AltrisMonitoring"})
    for: 90s
    labels:
      severity: critical
    annotations:
      summary: "Node-Exporter-Server-Monitoring down"
      description: "Node-exporter-Server-Monitoring container is down for more than 90 seconds."

  - alert: nodeexporter_high_cpu
    expr: sum(rate(container_cpu_usage_seconds_total{name="server-monitoring"}[1m])) / count(node_cpu_seconds_total{mode="system"}) * 100 > 10
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Node-Exporter-Server-Monitoring high CPU usage"
      description: "node-exporter-Server-Monitoring CPU usage is {{ humanize $value}}%."

  - alert: nodeexporter_high_memory
    expr: sum(container_memory_usage_bytes{name="server-monitoring"}) > 1200000000
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Node-Exporter-Server-Monitoring high memory usage"
      description: "node-exporter-Server-Monitoring memory consumption is at {{ humanize $value}}."

#########################################################################################################
  # This rule can be very noisy in dynamic infra with legitimate container start/stop/deployment.
  - alert: ContainerKilled
    expr: time() - container_last_seen > 60
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Container killed (instance {{ $labels.instance }})
      description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
